//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HISDataEntities : DbContext
    {
        public HISDataEntities()
            : base("name=HISDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SYS_USERROLEMAPPING> SYS_USERROLEMAPPING { get; set; }
        public virtual DbSet<SYS_Action> SYS_Action { get; set; }
        public virtual DbSet<SYS_ROLEACTIONMAPPING> SYS_ROLEACTIONMAPPING { get; set; }
        public virtual DbSet<SYS_ROLE> SYS_ROLE { get; set; }
        public virtual DbSet<SYS_ITEMMENU> SYS_ITEMMENU { get; set; }
        public virtual DbSet<SYS_Department> SYS_Department { get; set; }
        public virtual DbSet<SYS_USERINFO> SYS_USERINFO { get; set; }
    }
}
