//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USERINFO
    {
        public int ID { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string LoginName { get; set; }
        public string PASSWORD { get; set; }
        public string NAME { get; set; }
        public Nullable<int> AGE { get; set; }
        public Nullable<long> SEX { get; set; }
        public string PHONE { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string Tel { get; set; }
        public string Position { get; set; }
        public string HeadImg { get; set; }
    }
}
