//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Action
    {
        public int ID { get; set; }
        public string ActionName { get; set; }
        public string ActionNum { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string DESC { get; set; }
        public Nullable<int> ActionMenu { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
